<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('categories')->pluck('id', 'slug');
        // Get a demo seller (first active user or create placeholder)
        $sellerId = DB::table('users')->value('id');

        if (!$sellerId || $categories->isEmpty()) {
            $this->command->warn('Skipping ProductSeeder: no users or categories found. Run UserSeeder and CategorySeeder first.');
            return;
        }

        $products = [
            // Sea Fish
            [
                'name' => 'Premium Seer Fish (Vanjiram)',
                'slug' => 'premium-seer-fish-vanjiram',
                'category' => 'sea-fish',
                'description' => 'The king of Indian seafood. Seer fish (Vanjiram) is prized for its firm, white flesh and rich flavour. Caught fresh daily from the Bay of Bengal. Perfect for frying, grilling, and curry.',
                'price' => 950.00,
                'sale_price' => 850.00,
                'unit' => 'kg',
                'origin' => 'Bay of Bengal, Tamil Nadu',
                'freshness_notes' => 'Caught within 24 hours. Kept in chilled seawater. No preservatives used.',
                'is_featured' => true,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg', '2kg'],
            ],
            [
                'name' => 'Red Snapper (Sankara)',
                'slug' => 'red-snapper-sankara',
                'category' => 'sea-fish',
                'description' => 'Mild, sweet flavour with firm texture. Red Snapper is a favourite for South Indian fish curries. Sourced directly from local fishermen.',
                'price' => 700.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Rameswaram, Tamil Nadu',
                'freshness_notes' => 'Fresh catch. Cleaned and scaled on request.',
                'is_featured' => true,
                'is_popular' => false,
                'weight_options' => ['500g', '1kg'],
            ],
            [
                'name' => 'Kingfish (Ayala)',
                'slug' => 'kingfish-ayala',
                'category' => 'sea-fish',
                'description' => 'Rich in Omega-3, Kingfish is perfect for fry and curry. Loved across coastal Tamil Nadu and Kerala for its delicious taste.',
                'price' => 550.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Gulf of Mannar',
                'freshness_notes' => 'Same-day catch delivery.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg', '2kg'],
            ],
            [
                'name' => 'Pomfret (Vavval)',
                'slug' => 'pomfret-vavval',
                'category' => 'sea-fish',
                'description' => 'A premium flat fish with delicate white flesh. Silver pomfret is excellent for shallow frying and grilling. Very low in bones.',
                'price' => 800.00,
                'sale_price' => 720.00,
                'unit' => 'kg',
                'origin' => 'West Coast, Tamil Nadu',
                'freshness_notes' => 'Fresh catch. No freezing.',
                'is_featured' => true,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg'],
            ],
            [
                'name' => 'Tuna (Soorai)',
                'slug' => 'tuna-soorai',
                'category' => 'sea-fish',
                'description' => 'Deep sea tuna, rich in protein and omega-3. Available whole or cut. Great for grilling, searing, and fish curries.',
                'price' => 450.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Deep Sea, Indian Ocean',
                'freshness_notes' => 'Blast frozen immediately after catch to preserve freshness.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['1kg', '2kg', '5kg'],
            ],
            // Prawns
            [
                'name' => 'Tiger Prawns',
                'slug' => 'tiger-prawns',
                'category' => 'prawns',
                'description' => 'Large, meaty tiger prawns with excellent texture. Perfect for prawn masala, biryani, and grilling. Deveined and cleaned on request.',
                'price' => 750.00,
                'sale_price' => 680.00,
                'unit' => 'kg',
                'origin' => 'Muttom, Tamil Nadu',
                'freshness_notes' => 'Farm-raised in clean water. No antibiotics used.',
                'is_featured' => true,
                'is_popular' => true,
                'weight_options' => ['250g', '500g', '1kg'],
            ],
            [
                'name' => 'White Prawns (Vannamei)',
                'slug' => 'white-prawns-vannamei',
                'category' => 'prawns',
                'description' => 'Mild, sweet flavour. White prawns are versatile and perfect for quick stir-fries, curries, and snacks. Available peeled or with shell.',
                'price' => 580.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Tuticorin, Tamil Nadu',
                'freshness_notes' => 'Fresh batch every morning.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['250g', '500g', '1kg'],
            ],
            [
                'name' => 'Freshwater Prawns (Chemeen)',
                'slug' => 'freshwater-prawns-chemeen',
                'category' => 'prawns',
                'description' => 'Sweet, juicy freshwater prawns from backwater regions. Popular in Kerala-style preparations.',
                'price' => 650.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Backwaters, Kerala',
                'freshness_notes' => 'Live delivery where available.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['500g', '1kg'],
            ],
            // Crabs
            [
                'name' => 'Live Mud Crab',
                'slug' => 'live-mud-crab',
                'category' => 'crabs',
                'description' => 'Live mud crabs sourced from mangrove regions. Full of roe in season. Best for crab curry, pepper crab, and steaming.',
                'price' => 900.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Pichavaram Mangroves, Tamil Nadu',
                'freshness_notes' => 'Delivered alive and active. Same-day delivery only.',
                'is_featured' => true,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg', '2kg'],
            ],
            [
                'name' => 'Blue Swimming Crab',
                'slug' => 'blue-swimming-crab',
                'category' => 'crabs',
                'description' => 'Leaner than mud crab with sweet, delicate flesh. Popular in coastal Karnataka and Tamil Nadu cuisines.',
                'price' => 650.00,
                'sale_price' => 580.00,
                'unit' => 'kg',
                'origin' => 'Chennai Coast',
                'freshness_notes' => 'Chilled immediately after landing.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['500g', '1kg'],
            ],
            // River Fish
            [
                'name' => 'Rohu Fish',
                'slug' => 'rohu-fish',
                'category' => 'river-fish',
                'description' => 'One of the most popular freshwater fish in India. Rohu has a mild flavour and firm flesh, excellent for fish fry and curry.',
                'price' => 280.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Freshwater Farms, Andhra Pradesh',
                'freshness_notes' => 'Farm-raised in certified clean water.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg', '2kg'],
            ],
            [
                'name' => 'Katla Fish',
                'slug' => 'katla-fish',
                'category' => 'river-fish',
                'description' => 'Large-headed freshwater fish with rich, oily flesh. A staple of Bengali cuisine but beloved across India.',
                'price' => 320.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Freshwater Farms, West Bengal',
                'freshness_notes' => 'Fresh catch. Cleaned and cut on request.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['1kg', '2kg'],
            ],
            // Shellfish
            [
                'name' => 'Squid (Kanava)',
                'slug' => 'squid-kanava',
                'category' => 'shellfish',
                'description' => 'Fresh squid rings and whole squid. Perfect for seafood fried rice, masala, and grilled preparations.',
                'price' => 480.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Kanyakumari Coast',
                'freshness_notes' => 'Cleaned and ready to cook.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['250g', '500g', '1kg'],
            ],
            [
                'name' => 'Green Mussels (Kallummakkai)',
                'slug' => 'green-mussels-kallummakkai',
                'category' => 'shellfish',
                'description' => 'Fresh green mussels from coastal waters. Great for steaming, curries, and seafood platters. Rich in zinc and iron.',
                'price' => 350.00,
                'sale_price' => 300.00,
                'unit' => 'kg',
                'origin' => 'Muttom, Tamil Nadu',
                'freshness_notes' => 'Live mussels in shell. Cook within 24 hours.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['500g', '1kg'],
            ],
            // Dry Fish
            [
                'name' => 'Nethili Dry Fish (Anchovies)',
                'slug' => 'nethili-dry-fish-anchovies',
                'category' => 'dry-fish',
                'description' => 'Sun-dried anchovies, a staple of South Indian coastal cuisine. Used in chutneys, rice, and traditional curries.',
                'price' => 250.00,
                'sale_price' => null,
                'unit' => '250g',
                'origin' => 'Rameswaram, Tamil Nadu',
                'freshness_notes' => 'Naturally sun-dried. No artificial preservatives.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['250g', '500g', '1kg'],
            ],
            [
                'name' => 'Dry Seer Fish (Vathal)',
                'slug' => 'dry-seer-fish-vathal',
                'category' => 'dry-fish',
                'description' => 'Premium dry seer fish, salted and sun-dried. Excellent flavour enhancer for rice and traditional South Indian meals.',
                'price' => 650.00,
                'sale_price' => null,
                'unit' => '500g',
                'origin' => 'Nagapattinam, Tamil Nadu',
                'freshness_notes' => 'Traditional salt-cured process. Long shelf life.',
                'is_featured' => false,
                'is_popular' => false,
                'weight_options' => ['250g', '500g'],
            ],
            // Special Catch
            [
                'name' => 'Lobster (Iral)',
                'slug' => 'lobster-iral',
                'category' => 'special-catch',
                'description' => 'Premium spiny lobster from the Palk Strait. A luxury seafood experience. Available whole or split. Order in advance.',
                'price' => 2200.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Palk Strait, Tamil Nadu',
                'freshness_notes' => 'Live delivery. Pre-order required.',
                'is_featured' => true,
                'is_popular' => false,
                'weight_options' => ['500g', '1kg'],
            ],
            [
                'name' => 'Barramundi (Koduva)',
                'slug' => 'barramundi-koduva',
                'category' => 'special-catch',
                'description' => 'A prized coastal fish with delicate, buttery flavour. Excellent for whole-fish preparations. Limited availability.',
                'price' => 750.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Coastal Tamil Nadu',
                'freshness_notes' => 'Seasonal catch. Available October to February.',
                'is_featured' => true,
                'is_popular' => false,
                'weight_options' => ['1kg', '2kg'],
            ],
            // Fresh Fish
            [
                'name' => 'Milkfish (Paal Kendai)',
                'slug' => 'milkfish-paal-kendai',
                'category' => 'fresh-fish',
                'description' => 'Farm-raised milkfish with soft, milky white flesh. Great for steaming and grilling. Low bones with proper preparation.',
                'price' => 380.00,
                'sale_price' => 350.00,
                'unit' => 'kg',
                'origin' => 'Aquaculture Farms, Tamil Nadu',
                'freshness_notes' => 'Harvested fresh daily.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg'],
            ],
            [
                'name' => 'Mackerel (Ayala / Bangda)',
                'slug' => 'mackerel-ayala-bangda',
                'category' => 'fresh-fish',
                'description' => 'Rich in Omega-3 and intensely flavourful. Mackerel is perfect for spicy fish fry, grilling, and South Indian curries.',
                'price' => 320.00,
                'sale_price' => null,
                'unit' => 'kg',
                'origin' => 'Kochi, Kerala',
                'freshness_notes' => 'Same-day catch. Cleaned on request.',
                'is_featured' => false,
                'is_popular' => true,
                'weight_options' => ['500g', '1kg', '2kg'],
            ],
        ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category']] ?? null;
            if (!$categoryId) continue;

            DB::table('products')->insertOrIgnore([
                'id' => (string) Str::uuid(),
                'seller_id' => $sellerId,
                'category_id' => $categoryId,
                'name' => $product['name'],
                'slug' => $product['slug'],
                'full_description' => $product['description'],
                'short_description' => substr($product['description'], 0, 100),
                'price' => $product['price'],
                'sale_price' => $product['sale_price'] ?? null,
                'weight_unit' => $product['unit'],
                'minimum_order_quantity' => 0.25,
                'product_status' => 'PUBLISHED',
                'stock_status' => 'IN_STOCK',
                'available_quantity' => 10,
                'is_featured' => $product['is_featured'],
                'is_popular' => $product['is_popular'],
                'origin_location' => $product['origin'],
                'freshness_hours' => 24,
                'view_count' => rand(10, 500),
                'meta_title' => $product['name'] . ' | Kadal2Kadaai',
                'meta_description' => substr($product['description'], 0, 160),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
