import { SeafoodProduct, TodayPurchaseItem, HarborArrival, CustomerReview } from './types';

export const SEAFOOD_PRODUCTS: SeafoodProduct[] = [
  {
    id: 'prod-seer-fish-premium',
    subCategory: 'Sea fish',
    name: 'Vanjiram (Seer Fish)',
    tamilName: 'வஞ்சரம் மீன்',
    category: 'Fish',
    price: 1250,
    image: '/images/vanjiram-seer-fish-500g-slice-cut-cubes-1300rs.jpg',
    rating: 4.9,
    reviewsCount: 450,
    freshnessBadge: 'Ultra Fresh • Kasimedu Dawn',
    tag: 'Signature Catch',
    harborLocation: 'Rameswaram coastal area',
    description: 'The monarch of South Indian table fish. Firm, delicious meaty flesh with a single central bone. Best for the iconic Tamil Nadu fish fry.',
    availableWeights: ['500g', '1kg', '2kg'],
    availableCuts: ['Steaks / Slices', 'Whole Cleaned'],
    isPopular: true
  },
  {
    id: 'prod-silver-pomfret-large',
    subCategory: 'Sea fish',
    name: 'Pomfret (Vavval)',
    tamilName: 'வெள்ளை வாவல்',
    category: 'Fish',
    price: 980,
    image: '/images/vellai-vavval-chinese-pomfret-500g-800rs.jpg',
    rating: 4.9,
    reviewsCount: 320,
    freshnessBadge: 'Harbor Fresh • Silver Skin',
    tag: 'Ocean Delicacy',
    harborLocation: 'Rameswaram coastal area',
    description: 'Mild flavor and buttery texture. A premium white pomfret that melts in your mouth.',
    availableWeights: ['500g (2 pcs)', '1kg (3 pc)'],
    availableCuts: ['Whole Cleaned (With Slits)', 'Steaks'],
    isPopular: true
  },
  {
    id: 'prod-white-snapper',
    subCategory: 'Sea fish',
    name: 'White Snapper',
    tamilName: 'வெள்ளை சங்கரா',
    category: 'Fish',
    price: 650,
    image: '/images/white-snapper-korrukkai-fish-500g-slice-cut-400rs.jpg',
    rating: 4.8,
    reviewsCount: 156,
    freshnessBadge: 'Pristine White • Crystal Eyes',
    tag: 'Exotic',
    description: 'Delicate white meat with a subtle sweet flavor. Highly prized for its clean taste and firm texture.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole Cleaned', 'Curry Cut'],
    isPopular: false
  },
  {
    id: 'prod-red-snapper-ruby',
    subCategory: 'Sea fish',
    name: 'Red Snapper',
    tamilName: 'சங்கரா மீன்',
    category: 'Fish',
    price: 620,
    image: '/images/red-snapper-fish-500g-slice-cubes-cut-400rs.jpg',
    rating: 4.8,
    reviewsCount: 210,
    freshnessBadge: 'Deep Sea Catch • Ruby Red',
    tag: 'Deep Sea',
    harborLocation: 'Tuticorin Harbor',
    description: 'Nutty, sweet flavor with firm white meat. A versatile fish for grilling, steaming or curries.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole Cleaned', 'Curry Cut'],
    isPopular: true
  },
  {
    id: 'prod-halibut-nakkumeen',
    subCategory: 'Sea fish',
    name: 'Halibut (Nakkumeen)',
    tamilName: 'நாக்குமீன்',
    category: 'Fish',
    price: 820,
    image: '/images/nakkumeen-halibut-fish-500g-slice-cut-400rs.jpg',
    rating: 4.7,
    reviewsCount: 64,
    freshnessBadge: 'Harbor Landing • Deep Water',
    tag: 'Gourmet',
    description: 'Large, flat seafish with a unique texture. Lean white meat that remains moist when cooked.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Fillets', 'Steaks'],
    isPopular: false
  },
  {
    id: 'prod-barramundi-koduva',
    subCategory: 'Sea fish',
    name: 'Koduva Fish (Sea Bass)',
    tamilName: 'கொடுவா மீன்',
    category: 'Fish',
    price: 850,
    image: '/images/asal-koduva-sea-bass-500g-slice-cut-500rs.jpg',
    rating: 4.9,
    reviewsCount: 155,
    freshnessBadge: 'Ultra Fresh • Firm Flake',
    tag: 'Chef Choice',
    description: 'Luxurious white fish with a buttery flavor. Ideal for high-end Continental and Indian pan-sears.',
    availableWeights: ['500g', '1kg', '2kg'],
    availableCuts: ['Fillets', 'Steaks', 'Whole cleaned'],
    isPopular: true
  },
  {
    id: 'prod-mahi-mahi',
    subCategory: 'Sea fish',
    name: 'Mahi Mahi (Parla)',
    tamilName: 'பார்லா மீன்',
    category: 'Fish',
    price: 780,
    image: '/images/parla-mahi-mahi-fish-500g-boneless-fillets-cubes-500rs.jpg',
    rating: 4.8,
    reviewsCount: 42,
    freshnessBadge: 'Ocean Bright • Firm Texture',
    tag: 'High Protein',
    description: 'Lean and firm meat with a mild, sweet flavor. Famous for its colorful appearance and delicious steaks.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Steaks', 'Fillets'],
    isPopular: false
  },
  {
    id: 'prod-basa-fish',
    subCategory: 'Sea fish',
    name: 'Basa Fish',
    tamilName: 'பாசா மீன்',
    category: 'Fish',
    price: 450,
    image: '/images/basa-fish-pangasius-500g-slice-cut-200rs.jpg',
    rating: 4.6,
    reviewsCount: 280,
    freshnessBadge: 'Clean Processed • Soft Meat',
    tag: 'Easy Cooking',
    description: 'Extremely popular for its soft texture and lack of strong "fishy" odor. Perfect for fish fingers and frying.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Fillets (Boneless)', 'Cubes'],
    isPopular: true
  },
  {
    id: 'prod-kalavan-grouper',
    subCategory: 'Sea fish',
    name: 'Kalavan Fish (Grouper)',
    tamilName: 'கலவான் மீன்',
    category: 'Fish',
    price: 920,
    image: '/images/kalavan-grouper-fish-500g-slice-boneless-fillets-500rs.jpg',
    rating: 4.9,
    reviewsCount: 76,
    freshnessBadge: 'Harbor Fresh • Solid Texture',
    tag: 'Gourmet Choice',
    description: 'Heavy, hearty fish with large flakes. Excellent for steaming and hearty fish curries.',
    availableWeights: ['1kg (Large)', '500g'],
    availableCuts: ['Whole Cleaned', 'Steaks'],
    isPopular: false
  },
  {
    id: 'prod-milk-shark-sura',
    subCategory: 'Sea fish',
    name: 'Sura Fish (Baby Shark)',
    tamilName: 'சுறா மீன்',
    category: 'Fish',
    price: 550,
    image: '/images/pal-sura-milk-shark-500g-cubes-cut-550rs.jpg',
    rating: 4.8,
    reviewsCount: 190,
    freshnessBadge: 'Harbor Fresh • Super Clean',
    tag: 'Healing Power',
    description: 'Traditional coastal choice for nutritional value. Delicate meat with soft central cartilage.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Curry Cut', 'Minced (For Puttu)'],
    isPopular: true
  },
  {
    id: 'prod-cobia-kadal-viral',
    subCategory: 'Sea fish',
    name: 'Kadal Viral (Cobia)',
    tamilName: 'கடல் விரால்',
    category: 'Fish',
    price: 1100,
    image: '/images/kadal-viral-cobia-fish-500g-slice-cut-cubes-410rs.jpg',
    rating: 4.9,
    reviewsCount: 54,
    freshnessBadge: 'Deep Sea • Firm & Rich',
    tag: 'Delicacy',
    description: 'Often compared to King Seer Fish for its firm texture. Rich in fats and flavor, perfect for grilling.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Steaks', 'Fillets'],
    isPopular: false
  },
  {
    id: 'prod-pearl-spot-karimeen',
    subCategory: 'Sea fish',
    name: 'Karimeen (Pearl Spot)',
    tamilName: 'கரிமீன்',
    category: 'Fish',
    price: 880,
    image: '/images/karimeen-pearl-spot-500g-whole-fish-head-on-slice-cut-350rs.jpg',
    rating: 4.9,
    reviewsCount: 92,
    freshnessBadge: 'Backwater Fresh • Speckled Scales',
    tag: 'Rare Catch',
    description: 'The legendary backwater delight. Exquisite flavor when steamed in banana leaves (Karimeen Pollichathu).',
    availableWeights: ['500g (2-3 pcs)', '1kg'],
    availableCuts: ['Whole Cleaned (With Slits)'],
    isPopular: false
  },
  {
    id: 'prod-silver-belly-karapodi',
    subCategory: 'Sea fish',
    name: 'Silver Belly (Karapodi)',
    tamilName: 'காரப்பொடி மீன்',
    category: 'Fish',
    price: 380,
    image: '/images/karapodi-silver-belly-fish-500g-slice-cut-300rs.jpg',
    rating: 4.6,
    reviewsCount: 124,
    freshnessBadge: 'Morning Landed • Shiny Silver',
    tag: 'Daily Catch',
    description: 'Small, rounded fish with a distinct taste. Best enjoyed crispy fried or in a thin, spicy curry.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole Cleaned'],
    isPopular: false
  },
  {
    id: 'prod-golden-trevally',
    subCategory: 'Sea fish',
    name: 'Trevally (Parai)',
    tamilName: 'பாறை மீன்',
    category: 'Fish',
    price: 580,
    image: '/images/parai-trevally-fish-500g-slice-cut-450rs.jpg',
    rating: 4.7,
    reviewsCount: 95,
    freshnessBadge: 'Freshly Landed • Golden Fins',
    tag: 'Trending',
    description: 'Rich, oily fish with a distinct flavor. Highly prized in coastal cuisine for its healthy fats.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Steaks', 'Curry Cut'],
    isPopular: false
  },
  {
    id: 'prod-emperor-vila',
    subCategory: 'Sea fish',
    name: 'Emperor Fish (Villai)',
    tamilName: 'விளா மீன்',
    category: 'Fish',
    price: 680,
    image: '/images/villai-meen-emperor-fish-500g-slice-cut-450rs.jpg',
    rating: 4.7,
    reviewsCount: 88,
    freshnessBadge: 'Deep Sea • Pearl Scales',
    tag: 'Unique Taste',
    description: 'Mild, sweet flavor with a firm texture. Highly sought after for its refined taste.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole Cleaned', 'Curry Cut'],
    isPopular: false
  },
  {
    id: 'prod-barracuda-sheela',
    subCategory: 'Sea fish',
    name: 'Sheela Barracuda',
    tamilName: 'ஊளி / ஷீலா மீன்',
    category: 'Fish',
    price: 520,
    image: '/images/sheela-barracuda-500g-slice-cut-400rs.jpg',
    rating: 4.7,
    reviewsCount: 142,
    freshnessBadge: 'Dawn Landed • Razor Sharp',
    tag: 'Best for Fry',
    description: 'Robust flavor and firm texture. The top choice for spicy fish fry in Tamil households.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Curry Cut', 'Steaks'],
    isPopular: true
  },
  {
    id: 'prod-anchovy-nethili',
    subCategory: 'Sea fish',
    name: 'Nithili Anchovy',
    tamilName: 'நெத்திலி மீன்',
    category: 'Fish',
    price: 320,
    image: '/images/nethili-anchovy-500g-headless-275rs.jpg',
    rating: 4.8,
    reviewsCount: 175,
    freshnessBadge: 'Morning Harvest • Pristine',
    tag: 'Popular',
    description: 'Delicate, small fish with a unique taste. Ideal for crispy deep frying with a spicy coating.',
    availableWeights: ['500g'],
    availableCuts: ['Whole Cleaned'],
    isPopular: true
  },
  {
    id: 'prod-catla-freshwater',
    subCategory: 'Sea fish',
    name: 'Cutla (Catla)',
    tamilName: 'கட்லா மீன்',
    category: 'Fish',
    price: 360,
    image: '/images/cutla-fish-500g-slice-cut-160rs.jpg',
    rating: 4.7,
    reviewsCount: 112,
    freshnessBadge: 'River Delta Fresh • Large Scale',
    tag: 'Nutritious',
    description: 'Major Indian carp, famous for its sweet flavor and soft texture. Preferred for large steaks.',
    availableWeights: ['1kg (Medium)', '2kg (Large)'],
    availableCuts: ['Steaks / slices', 'Curry Cut'],
    isPopular: true
  },
  {
    id: 'prod-spiny-lobster',
    subCategory: 'Jumbo sea lobster',
    name: 'Spiny Rock Lobster',
    tamilName: 'சிங்கி நண்டு / சிங்க இறால்',
    category: 'Lobster',
    price: 2499,
    image: '/images/lobsters-1kg-2000rs.jpg',
    rating: 4.9,
    reviewsCount: 45,
    freshnessBadge: 'Deep Sea • Live On Arrival',
    tag: 'Ultra Luxury',
    description: 'The pinnacle of seafood luxury. Sourced from the deep rocky seabeds around Tuticorin. Sweet, succulent tail meat that needs minimal seasoning.',
    availableWeights: ['500g (1 Long Pc)', '1kg (2 Pcs)'],
    availableCuts: ['Whole Live', 'Split Cleaned'],
    isPopular: true
  },
  {
    id: 'prod-blue-crab-mandapam',
    subCategory: 'Blue crab',
    name: 'Premium Blue Crab',
    tamilName: 'நீர் நண்டு',
    category: 'Crab',
    price: 749,
    image: '/images/blue-crab-big-500g-550rs.jpg',
    rating: 4.8,
    reviewsCount: 230,
    freshnessBadge: 'Live Catch • Sweet Meat',
    tag: 'Best Seller',
    description: 'Directly sourced from Mandapam. Sweet, succulent meat perfect for spicy pepper stir-fries.',
    availableWeights: ['1kg (Large)', '1kg (Medium)'],
    availableCuts: ['Whole Live', 'Cleaned & Split'],
    isPopular: true
  },
  {
    id: 'prod-tiger-prawns-jumbo',
    subCategory: 'Tiger prawns',
    name: 'Jumbo Tiger Prawns',
    tamilName: 'மடவை இறால்',
    category: 'Prawns',
    price: 890,
    image: '/images/tiger-prawns-10-15-counts-500g-850rs.jpg',
    rating: 4.9,
    reviewsCount: 310,
    freshnessBadge: 'Plump & Juicy • Hand Picked',
    tag: 'Exotic',
    description: 'Large, sweet tiger prawns. Best for butter garlic tossing or tandoori marination.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Peeled & Deveined', 'Shell-on'],
    isPopular: true
  },
  {
    id: 'prod-indian-squid',
    subCategory: 'Sea fish',
    name: 'Squid (Kanava)',
    tamilName: 'கணவா',
    category: 'Fish',
    price: 480,
    image: '/images/kadama-squid-500g-ring-cut-350rs.jpg',
    rating: 4.6,
    reviewsCount: 145,
    freshnessBadge: 'Pier Fresh • Translucent',
    tag: 'Coastal Essential',
    description: 'Cleaned, tender squid rings. Perfect for deep frying or spicy masalas.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Rings Cleaned', 'Whole Cleaned'],
    isPopular: false
  },
  {
    id: 'prod-tuna-fresh',
    subCategory: 'Sea fish',
    name: 'Soorai Tuna Fish',
    tamilName: 'சூரை மீன்',
    category: 'Fish',
    price: 720,
    image: '/images/soorai-tuna-fish-500g-cubes-cut-500rs.jpg',
    rating: 4.7,
    reviewsCount: 130,
    freshnessBadge: 'Deep Sea • Deep Red',
    tag: 'High Protein',
    description: 'Hand-cut tuna loins. High in Omega-3. Rich, satisfying texture akin to premium tenderloin.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Boneless Steaks', 'Cubes'],
    isPopular: false
  },
  {
    id: 'prod-tilapia-fish',
    subCategory: 'Sea fish',
    name: 'Tilapia Fish',
    tamilName: 'திலாப்பியா',
    category: 'Fish',
    price: 280,
    image: '/images/jilebi-tilapia-500g-slice-cut-175rs.jpg',
    rating: 4.5,
    reviewsCount: 88,
    freshnessBadge: 'Farm Fresh • Sustained',
    tag: 'Mild Flavor',
    description: 'A neutral, mild-flavored fish that takes on seasonings beautifully. Popular for pan-frying.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole Cleaned', 'Fillets'],
    isPopular: false
  },
  {
    id: 'prod-sardine-mathi',
    subCategory: 'Sea fish',
    name: 'Mathi (Indian Oil Sardine)',
    tamilName: 'மத்தி மீன்',
    category: 'Fish',
    price: 240,
    image: '/images/matthi-sardine-fish-500g-head-on-whole-fish-250rs.jpg',
    rating: 4.5,
    reviewsCount: 220,
    freshnessBadge: 'Silver Scales • Dawn Catch',
    tag: 'Superfood',
    description: 'Loaded with Omega-3. Smaller fish with intense flavor, perfect for traditional spicy curries.',
    availableWeights: ['500g', '1kg'],
    availableCuts: ['Whole (Head off)', 'Whole Cleaned'],
    isPopular: true
  },
  {
    id: "prod-fresh-water-prawns-60-80",
    subCategory: 'Fresh water prawn',
    name: "Fresh Water Prawns (60-80 Counts)",
    category: "Prawns",
    price: 300,
    image: "/images/fresh-water-prawns-500g-60-80-counts-350rs.jpg",
    rating: 4.6,
    reviewsCount: 120,
    freshnessBadge: "Freshly Caught",
    description: "Perfect for curries and fries. 60-80 counts per 500g.",
    availableWeights: ["500g"],
    availableCuts: ["Cleaned & Deveined"],
    isPopular: false
  },
  {
    id: "prod-sea-white-prawns-10-15",
    subCategory: 'Sea whiter prawn',
    name: "Sea White Prawns (10-15 Counts)",
    category: "Prawns",
    price: 850,
    image: "/images/sea-white-prawns-10-15-counts-500g-850rs.jpg",
    rating: 4.8,
    reviewsCount: 200,
    freshnessBadge: "Jumbo Size",
    description: "Large sea white prawns, 10-15 counts per 500g. Ideal for grilling or biryani.",
    availableWeights: ["500g"],
    availableCuts: ["Cleaned & Deveined"],
    isPopular: true
  },
  {
    id: "prod-sea-white-prawns-60-80",
    subCategory: 'Sea whiter prawn',
    name: "Sea White Prawns (60-80 Counts)",
    category: "Prawns",
    price: 300,
    image: "/images/sea-white-prawns-500g-60-80-counts-300rs.jpg",
    rating: 4.7,
    reviewsCount: 150,
    freshnessBadge: "Everyday Catch",
    description: "Medium-sized sea white prawns, 60-80 counts per 500g.",
    availableWeights: ["500g"],
    availableCuts: ["Cleaned & Deveined"],
    isPopular: false
  },
  {
    id: "prod-tiger-prawns-10-15",
    subCategory: 'Tiger prawns',
    name: "Tiger Prawns (10-15 Counts)",
    category: "Prawns",
    price: 850,
    image: "/images/tiger-prawns-10-15-counts-500g-850rs.jpg",
    rating: 4.9,
    reviewsCount: 310,
    freshnessBadge: "Premium Catch",
    description: "Premium large tiger prawns, 10-15 counts per 500g.",
    availableWeights: ["500g"],
    availableCuts: ["Cleaned & Deveined"],
    isPopular: true
  },
  {
    id: "prod-tiger-prawns-30",
    subCategory: 'Tiger prawns',
    name: "Tiger Prawns (30 Counts)",
    category: "Prawns",
    price: 600,
    image: "/images/tiger-prawns-500g-30-counts-600rs.jpg",
    rating: 4.8,
    reviewsCount: 220,
    freshnessBadge: "Freshly Caught",
    description: "Tiger prawns, 30 counts per 500g. Great for curries and appetizers.",
    availableWeights: ["500g"],
    availableCuts: ["Cleaned & Deveined"],
    isPopular: true
  },
  {
    id: "prod-lobsters-1kg-2000rs",
    subCategory: 'Lobsters',
    name: "Lobsters",
    category: "Lobster",
    price: 2000,
    image: "/images/lobsters-1kg-2000rs.jpg",
    rating: 4.9,
    reviewsCount: 80,
    freshnessBadge: "Live Catch",
    description: "Premium fresh lobsters, 1kg.",
    availableWeights: ["1kg"],
    availableCuts: ["Whole Live"],
    isPopular: true
  },
  {
    id: "prod-three-spot-crab",
    subCategory: 'Three spot crab',
    name: "Three Spot Crab",
    category: "Crab",
    price: 450,
    image: "/images/crab-three-spot-500g-300rs.jpg",
    rating: 4.7,
    reviewsCount: 110,
    freshnessBadge: "Fresh Catch",
    description: "Fresh three spot crab, ideal for curries.",
    availableWeights: ["1kg"],
    availableCuts: ["Whole Cleaned"],
    isPopular: false
  },
  {
    id: "prod-live-green-mid-crab",
    subCategory: 'Live green mid crab',
    name: "Live Green Mid Crab",
    category: "Crab",
    price: 550,
    image: "/images/mud-crab-green-live-crab-1kg-2000rs.jpg",
    rating: 4.8,
    reviewsCount: 95,
    freshnessBadge: "Live Catch",
    description: "Live green mid crab, sweet and succulent.",
    availableWeights: ["1kg"],
    availableCuts: ["Whole Live"],
    isPopular: true
  },
  {
    id: "prod-jumbo-sea-lobster",
    subCategory: 'Jumbo sea lobster',
    name: "Jumbo Sea Lobster",
    category: "Lobster",
    price: 2800,
    image: "/images/lobsters-1kg-2000rs.jpg",
    rating: 4.9,
    reviewsCount: 150,
    freshnessBadge: "Ultra Premium",
    description: "Jumbo sea lobster, premium quality.",
    availableWeights: ["1kg"],
    availableCuts: ["Whole Live"],
    isPopular: true
  },
  {
    id: "prod-dry-fish",
    subCategory: 'Dry fish',
    name: "Premium Dry Fish Assortment",
    category: "Fish",
    price: 350,
    image: "/images/yeri-vavval-roopchand-500g-slice-cut-175rs.jpg",
    rating: 4.5,
    reviewsCount: 85,
    freshnessBadge: "Sun Dried",
    description: "Traditionally sun-dried premium fish.",
    availableWeights: ["500g"],
    availableCuts: ["Whole"],
    isPopular: false
  },
  {
    id: "prod-pure-water-fish",
    subCategory: 'Pure water fish',
    name: "Pure Water Fish",
    category: "Fish",
    price: 450,
    image: "/images/yeri-vavval-roopchand-500g-slice-cut-175rs.jpg",
    rating: 4.8,
    reviewsCount: 120,
    freshnessBadge: "Freshly Caught",
    description: "Sourced from crystal clear pure waters.",
    availableWeights: ["1kg"],
    availableCuts: ["Cleaned & Sliced"],
    isPopular: false
  },
  {
    id: "prod-fresh-water-fish-cat",
    subCategory: 'Fresh water fish',
    name: "Fresh Water Fish",
    category: "Fish",
    price: 380,
    image: "/images/yeri-vavval-roopchand-500g-slice-cut-175rs.jpg",
    rating: 4.6,
    reviewsCount: 150,
    freshnessBadge: "River Catch",
    description: "Freshly caught from local freshwater rivers.",
    availableWeights: ["1kg"],
    availableCuts: ["Cleaned & Sliced"],
    isPopular: true
  },
  {
    id: "prod-lake-water-fish",
    subCategory: 'Lake water fish',
    name: "Lake Water Fish",
    category: "Fish",
    price: 420,
    image: "/images/yeri-vavval-roopchand-500g-slice-cut-175rs.jpg",
    rating: 4.7,
    reviewsCount: 95,
    freshnessBadge: "Lake Catch",
    description: "Fresh from deep pristine lakes.",
    availableWeights: ["1kg"],
    availableCuts: ["Cleaned & Sliced"],
    isPopular: false
  },
  {
    id: "prod-frozen-fish",
    subCategory: 'Frozen fish',
    name: "Premium Frozen Fish",
    category: "Fish",
    price: 299,
    image: "/images/yeri-vavval-roopchand-500g-slice-cut-175rs.jpg",
    rating: 4.4,
    reviewsCount: 200,
    freshnessBadge: "Flash Frozen",
    description: "Flash-frozen at sea to lock in freshness.",
    availableWeights: ["1kg"],
    availableCuts: ["Fillets"],
    isPopular: true
  }
];

export const TODAY_PURCHASES: TodayPurchaseItem[] = [
  {
    id: 'pur-1',
    name: 'Vanjiram (Seer Fish)',
    image: '/images/vanjiram-seer-fish-500g-slice-cut-cubes-1300rs.jpg',
    demandMeter: 94,
    householdsPurchasedCount: 142,
    weightSelected: '1kg',
    cutType: 'Steaks / Slices',
    price: 1250,
    category: 'SEER FISH',
    tag: '🔥 Trending #1'
  },
  {
    id: 'pur-2',
    name: 'Sheela Barracuda',
    image: '/images/sheela-barracuda-500g-slice-cut-400rs.jpg',
    demandMeter: 82,
    householdsPurchasedCount: 89,
    weightSelected: '500g',
    cutType: 'Steaks',
    price: 520,
    category: 'BARRACUDA',
    tag: '✨ Best for Fry'
  },
  {
    id: 'pur-3',
    name: 'Pomfret (Vavval)',
    image: '/images/vellai-vavval-chinese-pomfret-500g-800rs.jpg',
    demandMeter: 88,
    householdsPurchasedCount: 112,
    weightSelected: '1kg',
    cutType: 'Whole Cleaned',
    price: 980,
    category: 'POMFRET',
    tag: '⚡ Popular Choice'
  }
];

export const HARBOR_ARRIVALS: HarborArrival[] = [
  {
    id: 'harbor-1',
    harborName: 'Kasimedu Fishing Harbor',
    district: 'Chennai',
    catchTime: '02:45 AM Today',
    arrivalCount: 215,
    freshnessIndex: 99,
    primaryCatcherBoat: 'Deep Sea Voyager',
    featuredFish: 'Seer Fish, Pomfret, Tuna, Shark'
  },
  {
    id: 'harbor-2',
    harborName: 'Tuticorin Harbor',
    district: 'Thoothukudi',
    catchTime: '03:30 AM Today',
    arrivalCount: 145,
    freshnessIndex: 98,
    primaryCatcherBoat: 'Ocean Pearl IV',
    featuredFish: 'Lobsters, Crabs, Snappers'
  }
];

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    name: 'Aravind Swamy',
    location: 'Adyar, Chennai',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
    rating: 5,
    comment: "The King Seer Fish was incredibly fresh. Arrived at 8:15 AM on ice. Perfect steaks for my mother's special recipe.",
    date: 'Today',
    verified: true
  },
  {
    id: 'rev-2',
    name: 'Deepika Raman',
    location: 'Anna Nagar, Chennai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
    rating: 5,
    comment: 'The Milk Shark was processed so cleanly! Rare to find this quality online. Highly recommended.',
    date: 'Yesterday',
    verified: true
  }
];